services:
    Github\Client:
        arguments:
            - '@Github\HttpClient\Builder'
        calls:
            - ['authenticate', ['%env(GITHUB_TOKEN)%', null, 'access_token_header']]

    Github\HttpClient\Builder:
        arguments:
            - '@?Http\Client\HttpClient'
            - '@?Http\Message\RequestFactory'
            - '@?Http\Message\StreamFactory'
